[package]
name = "cubic"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
btleplug = "0.9.0"
rand = "0.8.4"
# tokio = "1.13.0"
tokio = { version = "0.3", features = ["full"] }
tokio-compat-02 = "0.2.0"
uuid = "0.8.2"
